# netlify.toml
[build]
  publish = "."
  command = "echo 'Site statique prêt'"

# Configuration pour Sveltia CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Configuration Git Gateway pour l'authentification
[build.environment]
  NODE_VERSION = "18"

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers spécifiques pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration pour les fichiers de contenu
[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=300"