# admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

# Configuration des couleurs et du thème
collections:
  - name: "settings"
    label: "⚙️ Paramètres du site"
    files:
      - name: "general"
        label: "Paramètres généraux"
        file: "content/settings/general.yml"
        fields:
          - name: "site_name"
            label: "Nom du site"
            widget: "string"
            default: "Grossiste Alimentaire Pro"
          - name: "tagline"
            label: "Slogan"
            widget: "string"
            default: "Votre partenaire alimentaire de confiance"
          - name: "logo"
            label: "Logo"
            widget: "image"
            required: false
          - name: "favicon"
            label: "Favicon"
            widget: "image"
            required: false

      - name: "theme"
        label: "🎨 Couleurs et thème"
        file: "content/settings/theme.yml"
        fields:
          - name: "colors"
            label: "Couleurs"
            widget: "object"
            fields:
              - name: "primary"
                label: "Couleur principale"
                widget: "color"
                default: "#2c5530"
              - name: "primary_light"
                label: "Couleur principale claire"
                widget: "color"
                default: "#4a7c59"
              - name: "secondary"
                label: "Couleur secondaire"
                widget: "color"
                default: "#ff6b35"
              - name: "accent"
                label: "Couleur d'accent"
                widget: "color"
                default: "#a8d5ba"
              - name: "background"
                label: "Couleur de fond"
                widget: "color"
                default: "#ffffff"
              - name: "background_alt"
                label: "Couleur de fond alternative"
                widget: "color"
                default: "#f8fdf8"
              - name: "text"
                label: "Couleur du texte"
                widget: "color"
                default: "#333333"
              - name: "text_light"
                label: "Couleur du texte clair"
                widget: "color"
                default: "#666666"
          - name: "fonts"
            label: "Typographie"
            widget: "object"
            fields:
              - name: "primary_font"
                label: "Police principale"
                widget: "select"
                options:
                  - label: "Segoe UI"
                    value: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
                  - label: "Arial"
                    value: "Arial, sans-serif"
                  - label: "Helvetica"
                    value: "Helvetica, Arial, sans-serif"
                  - label: "Times New Roman"
                    value: "'Times New Roman', Times, serif"
                  - label: "Georgia"
                    value: "Georgia, serif"
                default: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"

      - name: "contact"
        label: "📞 Contact"
        file: "content/settings/contact.yml"
        fields:
          - name: "address"
            label: "Adresse complète"
            widget: "text"
            default: "123 Avenue du Commerce\nZone Industrielle Nord\n75000 Paris, France"
          - name: "phone"
            label: "Téléphone"
            widget: "string"
            default: "01 23 45 67 89"
          - name: "email"
            label: "Email"
            widget: "string"
            default: "contact@grossiste-alimentaire.fr"
          - name: "hours"
            label: "Horaires"
            widget: "object"
            fields:
              - name: "monday_friday"
                label: "Lundi - Vendredi"
                widget: "string"
                default: "6h00 - 18h00"
              - name: "saturday"
                label: "Samedi"
                widget: "string"
                default: "7h00 - 16h00"
              - name: "sunday"
                label: "Dimanche"
                widget: "string"
                default: "Fermé"

      - name: "social"
        label: "📱 Réseaux sociaux"
        file: "content/settings/social.yml"
        fields:
          - name: "facebook"
            label: "Facebook URL"
            widget: "string"
            required: false
          - name: "linkedin"
            label: "LinkedIn URL"
            widget: "string"
            required: false
          - name: "instagram"
            label: "Instagram URL"
            widget: "string"
            required: false
          - name: "twitter"
            label: "Twitter URL"
            widget: "string"
            required: false
          - name: "youtube"
            label: "YouTube URL"
            widget: "string"
            required: false

  - name: "pages"
    label: "📄 Pages"
    files:
      - name: "home"
        label: "Page d'accueil"
        file: "content/pages/home.yml"
        fields:
          - name: "hero"
            label: "Section Hero"
            widget: "object"
            fields:
              - name: "title"
                label: "Titre principal"
                widget: "string"
                default: "Votre Partenaire Grossiste Alimentaire de Confiance"
              - name: "subtitle"
                label: "Sous-titre"
                widget: "text"
                default: "Depuis plus de 20 ans, nous fournissons restaurants, épiceries et collectivités avec des produits alimentaires de qualité supérieure."
              - name: "cta_text"
                label: "Texte bouton d'action"
                widget: "string"
                default: "Demander un devis"
              - name: "cta_link"
                label: "Lien bouton d'action"
                widget: "string"
                default: "#contact"
              - name: "background_image"
                label: "Image de fond"
                widget: "image"
                required: false
          - name: "services_section"
            label: "Section Services"
            widget: "object"
            fields:
              - name: "title"
                label: "Titre de la section"
                widget: "string"
                default: "Nos Services"
              - name: "subtitle"
                label: "Sous-titre (optionnel)"
                widget: "text"
                required: false
          - name: "products_section"
            label: "Section Produits"
            widget: "object"
            fields:
              - name: "title"
                label: "Titre de la section"
                widget: "string"
                default: "Notre Catalogue"
              - name: "subtitle"
                label: "Sous-titre (optionnel)"
                widget: "text"
                required: false
          - name: "news_section"
            label: "Section Actualités"
            widget: "object"
            fields:
              - name: "title"
                label: "Titre de la section"
                widget: "string"
                default: "Actualités"
              - name: "subtitle"
                label: "Sous-titre (optionnel)"
                widget: "text"
                required: false

  - name: "services"
    label: "🛠️ Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Titre du service"
        widget: "string"
      - name: "icon"
        label: "Icône (emoji ou texte)"
        widget: "string"
        default: "🚚"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "features"
        label: "Caractéristiques"
        widget: "list"
        required: false
        field:
          name: "feature"
          label: "Caractéristique"
          widget: "string"
      - name: "order"
        label: "Ordre d'affichage"
        widget: "number"
        default: 1
      - name: "active"
        label: "Service actif"
        widget: "boolean"
        default: true

  - name: "products"
    label: "🛒 Produits"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Nom du produit/catégorie"
        widget: "string"
      - name: "category"
        label: "Catégorie"
        widget: "select"
        options:
          - "Viandes & Charcuterie"
          - "Produits Laitiers"
          - "Boulangerie & Pâtisserie"
          - "Fruits & Légumes"
          - "Épicerie Fine"
          - "Surgelés"
          - "Boissons"
          - "Produits d'Hygiène"
          - "Autre"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Image du produit"
        widget: "image"
        required: false
      - name: "icon"
        label: "Icône (emoji si pas d'image)"
        widget: "string"
        default: "📦"
      - name: "price_info"
        label: "Information prix (optionnel)"
        widget: "string"
        required: false
      - name: "features"
        label: "Caractéristiques"
        widget: "list"
        required: false
        field:
          name: "feature"
          label: "Caractéristique"
          widget: "string"
      - name: "featured"
        label: "Produit vedette"
        widget: "boolean"
        default: false
      - name: "order"
        label: "Ordre d'affichage"
        widget: "number"
        default: 1
      - name: "active"
        label: "Produit actif"
        widget: "boolean"
        default: true

  - name: "promotions"
    label: "🎯 Promotions"
    folder: "content/promotions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "title"
        label: "Titre de la promotion"
        widget: "string"
      - name: "highlight"
        label: "Texte mis en avant"
        widget: "string"
        default: "-20% sur tous les produits"
      - name: "description"
        label: "Description complète"
        widget: "text"
      - name: "discount"
        label: "Pourcentage/montant de réduction"
        widget: "string"
      - name: "conditions"
        label: "Conditions"
        widget: "text"
        required: false
      - name: "valid_from"
        label: "Valable à partir du"
        widget: "datetime"
      - name: "valid_until"
        label: "Valable jusqu'au"
        widget: "datetime"
      - name: "image"
        label: "Image de la promotion"
        widget: "image"
        required: false
      - name: "featured"
        label: "Promotion en vedette"
        widget: "boolean"
        default: false
      - name: "active"
        label: "Promotion active"
        widget: "boolean"
        default: true

  - name: "news"
    label: "📰 Actualités"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "title"
        label: "Titre de l'article"
        widget: "string"
      - name: "date"
        label: "Date de publication"
        widget: "datetime"
        default: ""
        format: "DD/MM/YYYY"
      - name: "excerpt"
        label: "Résumé/extrait"
        widget: "text"
      - name: "content"
        label: "Contenu complet"
        widget: "markdown"
      - name: "featured_image"
        label: "Image principale"
        widget: "image"
        required: false
      - name: "author"
        label: "Auteur"
        widget: "string"
        required: false
      - name: "tags"
        label: "Étiquettes"
        widget: "list"
        required: false
        field:
          name: "tag"
          label: "Étiquette"
          widget: "string"
      - name: "featured"
        label: "Article en vedette"
        widget: "boolean"
        default: false
      - name: "published"
        label: "Article publié"
        widget: "boolean"
        default: true

  - name: "testimonials"
    label: "💬 Témoignages"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "client_name"
        label: "Nom du client"
        widget: "string"
      - name: "company"
        label: "Entreprise"
        widget: "string"
      - name: "position"
        label: "Poste"
        widget: "string"
        required: false
      - name: "testimonial"
        label: "Témoignage"
        widget: "text"
      - name: "rating"
        label: "Note (1-5)"
        widget: "number"
        min: 1
        max: 5
        default: 5
      - name: "photo"
        label: "Photo du client"
        widget: "image"
        required: false
      - name: "featured"
        label: "Témoignage en vedette"
        widget: "boolean"
        default: false
      - name: "active"
        label: "Témoignage actif"
        widget: "boolean"
        default: true

  - name: "team"
    label: "👥 Équipe"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "name"
        label: "Nom complet"
        widget: "string"
      - name: "position"
        label: "Poste"
        widget: "string"
      - name: "bio"
        label: "Biographie"
        widget: "text"
      - name: "photo"
        label: "Photo"
        widget: "image"
        required: false
      - name: "email"
        label: "Email"
        widget: "string"
        required: false
      - name: "phone"
        label: "Téléphone"
        widget: "string"
        required: false
      - name: "order"
        label: "Ordre d'affichage"
        widget: "number"
        default: 1
      - name: "active"
        label: "Membre actif"
        widget: "boolean"
        default: true