backend:
  name: git-gateway
  branch: main

# Workflow avec branche staging pour économiser les builds
publish_mode: editorial_workflow

# Configuration Netlify Large Media
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
media_library:
  name: netlify-large-media
  config:
    publicKey: your-public-key

collections:
  # Configuration du site (simplifié)
  - name: "config"
    label: "⚙️ Configuration"
    files:
      - label: "Paramètres du site"
        name: "settings"
        file: "_data/settings.json"
        fields:
          - { label: "Nom du site", name: "siteName", widget: "string" }
          - { label: "Couleur principale", name: "primaryColor", widget: "color", default: "#007bff" }
          - { label: "Logo (optionnel)", name: "logo", widget: "image", required: false }
          
      - label: "Page d'accueil"
        name: "homepage"
        file: "_data/homepage.json"
        fields:
          - { label: "Titre principal", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subtitle", widget: "string" }
          - { label: "Description", name: "content", widget: "markdown" }
          
      - label: "Contact"
        name: "contact"
        file: "_data/contact.json"
        fields:
          - { label: "Téléphone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Adresse", name: "address", widget: "text" }

  # Produits (version simplifiée avec slug automatique)
  - name: "products"
    label: "🛍️ Produits"
    folder: "_products"
    create: true
    slug: "{{fields.name | slugify}}"
    fields:
      - { label: "Nom du produit", name: "name", widget: "string" }
      - { label: "Prix (€)", name: "price", widget: "number", value_type: "float", min: 0 }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image principale", name: "image", widget: "image" }
      - label: "Catégorie"
        name: "category"
        widget: "select"
        options:
          - { label: "📱 Électronique", value: "electronique" }
          - { label: "👕 Vêtements", value: "vetements" }
          - { label: "🏠 Maison", value: "maison" }
      # Champs optionnels cachés par défaut
      - { label: "En stock", name: "in_stock", widget: "boolean", default: true, required: false }
      - { label: "Produit vedette", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Images supplémentaires (optionnel)", name: "gallery", widget: "list", field: {name: "image", widget: "image"}, required: false }
      - { label: "Description détaillée (optionnel)", name: "body", widget: "markdown", required: false }

  # Services (simplifié)
  - name: "services"
    label: "🔧 Services"
    folder: "_services"
    create: true
    slug: "{{fields.title | slugify}}"
    fields:
      - { label: "Nom du service", name: "title", widget: "string" }
      - { label: "Prix", name: "price", widget: "string", default: "Sur devis" }
      - { label: "Description", name: "content", widget: "markdown" }
      # Champs optionnels
      - { label: "Image (optionnel)", name: "image", widget: "image", required: false }
      - { label: "Ordre d'affichage", name: "order", widget: "number", default: 1, required: false }

  # Promotions (simplifié)
  - name: "promotions"
    label: "🏷️ Promotions"
    folder: "_promotions"
    create: true
    slug: "{{fields.title | slugify}}"
    fields:
      - { label: "Titre de la promotion", name: "title", widget: "string" }
      - { label: "Nom du produit", name: "productName", widget: "string" }
      - { label: "Prix original (€)", name: "originalPrice", widget: "number", value_type: "float" }
      - { label: "Prix promotionnel (€)", name: "newPrice", widget: "number", value_type: "float" }
      - { label: "Image du produit", name: "productImage", widget: "image" }
      # Champs optionnels/automatiques
      - { label: "Réduction", name: "discount", widget: "string", default: "À calculer", required: false }
      - { label: "Description (optionnel)", name: "description", widget: "text", required: false }
      - { label: "Date de fin", name: "endDate", widget: "string", default: "À définir", required: false }
      - { label: "Active", name: "active", widget: "boolean", default: true, required: false }

  # Actualités (simplifié)
  - name: "news"
    label: "📰 Actualités"
    folder: "_news"
    create: true
    slug: "{{fields.title | slugify}}"
    fields:
      - { label: "Titre de l'article", name: "title", widget: "string" }
      - { label: "Description courte", name: "description", widget: "text" }
      - { label: "Image de couverture", name: "image", widget: "image" }
      - { label: "Contenu de l'article", name: "body", widget: "markdown" }
      # Champs automatiques/optionnels
      - { label: "Date", name: "date", widget: "datetime", default: "", required: false }
      - { label: "Auteur (optionnel)", name: "author", widget: "string", required: false }
      - { label: "Article en vedette", name: "featured", widget: "boolean", default: false, required: false }

# Interface simplifiée
editor:
  preview: false

# Configuration du workflow éditorial
editorial_workflow:
  publish_mode: editorial_workflow