# admin/config.yml - Version compatible Netlify CMS
backend:
  name: git-gateway
  branch: main

# Configuration média
media_folder: "assets/images"
public_folder: "/assets/images"

# Logo pour l'interface (optionnel)
logo_url: /assets/images/logo.png

# Collections simplifiées pour démarrer
collections:
  - name: "settings"
    label: "⚙️ Paramètres"
    files:
      - name: "general"
        label: "Paramètres généraux"
        file: "content/settings/general.json"
        fields:
          - name: "site_name"
            label: "Nom du site"
            widget: "string"
            default: "Grossiste Alimentaire Pro"
          - name: "tagline"
            label: "Slogan"
            widget: "string"
            default: "Votre partenaire alimentaire de confiance"

      - name: "colors"
        label: "🎨 Couleurs"
        file: "content/settings/colors.json"
        fields:
          - name: "primary"
            label: "Couleur principale"
            widget: "color"
            default: "#2c5530"
          - name: "secondary"
            label: "Couleur secondaire"
            widget: "color"
            default: "#ff6b35"
          - name: "accent"
            label: "Couleur d'accent"
            widget: "color"
            default: "#a8d5ba"

      - name: "contact"
        label: "📞 Contact"
        file: "content/settings/contact.json"
        fields:
          - name: "address"
            label: "Adresse"
            widget: "text"
            default: "123 Avenue du Commerce\n75000 Paris"
          - name: "phone"
            label: "Téléphone"
            widget: "string"
            default: "01 23 45 67 89"
          - name: "email"
            label: "Email"
            widget: "string"
            default: "contact@grossiste.fr"

  - name: "pages"
    label: "📄 Pages"
    files:
      - name: "home"
        label: "Page d'accueil"
        file: "content/pages/home.json"
        fields:
          - name: "hero_title"
            label: "Titre principal"
            widget: "string"
            default: "Votre Partenaire Grossiste Alimentaire"
          - name: "hero_description"
            label: "Description"
            widget: "text"
            default: "Depuis plus de 20 ans, nous fournissons des produits de qualité"
          - name: "cta_text"
            label: "Texte bouton"
            widget: "string"
            default: "Demander un devis"

  - name: "services"
    label: "🛠️ Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Titre"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "icon"
        label: "Icône (emoji)"
        widget: "string"
        default: "🚚"
      - name: "active"
        label: "Actif"
        widget: "boolean"
        default: true

  - name: "products"
    label: "🛒 Produits"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Nom du produit"
        widget: "string"
      - name: "category"
        label: "Catégorie"
        widget: "select"
        options:
          - "Viandes & Charcuterie"
          - "Produits Laitiers"
          - "Boulangerie"
          - "Fruits & Légumes"
          - "Épicerie"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "image"
        label: "Image"
        widget: "image"
        required: false
      - name: "price"
        label: "Prix indicatif"
        widget: "string"
        required: false

  - name: "news"
    label: "📰 Actualités"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "title"
        label: "Titre"
        widget: "string"
      - name: "date"
        label: "Date"
        widget: "datetime"
      - name: "excerpt"
        label: "Résumé"
        widget: "text"
      - name: "body"
        label: "Contenu"
        widget: "markdown"
      - name: "image"
        label: "Image"
        widget: "image"
        required: false

  - name: "promotions"
    label: "🎯 Promotions"
    folder: "content/promotions"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Titre"
        widget: "string"
      - name: "discount"
        label: "Réduction"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "text"
      - name: "valid_until"
        label: "Valable jusqu'au"
        widget: "datetime"
      - name: "active"
        label: "Active"
        widget: "boolean"
        default: true